"""Add DeploymentConfig and PolicyProfile

Revision ID: 1229e13df440
Revises: 7caf4af60a77
Create Date: 2026-09-03 19:39:04.086106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1229e13df440'
down_revision: Union[str, Sequence[str], None] = '7caf4af60a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_code'), 'otp_codes', ['code'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('deployment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.String(length=50), nullable=False),
    sa.Column('memory_limit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('policy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('max_critical', sa.Integer(), nullable=False),
    sa.Column('max_high', sa.Integer(), nullable=False),
    sa.Column('whitelisted_cves', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.add_column('deployments', sa.Column('access_url', sa.String(length=1024), nullable=True))
    op.add_column('scan_results', sa.Column('iac_json', sa.JSON(), nullable=True))
    op.add_column('scan_results', sa.Column('k8s_json', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('device_info', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('ip_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ip_address')
    op.drop_column('sessions', 'device_info')
    op.drop_column('scan_results', 'k8s_json')
    op.drop_column('scan_results', 'iac_json')
    op.drop_column('deployments', 'access_url')
    op.drop_table('policy_profiles')
    op.drop_table('deployment_configs')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_otp_codes_code'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('notifications')
    # ### end Alembic commands ###
