"""Add architecture fields to DeploymentConfig

Revision ID: b5e048d95b4f
Revises: 1229e13df440
Create Date: 2026-09-03 19:43:08.009555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e048d95b4f'
down_revision: Union[str, Sequence[str], None] = '1229e13df440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_configs', sa.Column('enable_redis', sa.Boolean(), nullable=False))
    op.add_column('deployment_configs', sa.Column('enable_postgres', sa.Boolean(), nullable=False))
    op.add_column('deployment_configs', sa.Column('ingress_host', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_configs', 'ingress_host')
    op.drop_column('deployment_configs', 'enable_postgres')
    op.drop_column('deployment_configs', 'enable_redis')
    # ### end Alembic commands ###
