apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-97daf9913d0d
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-97daf9913d0d
  template:
    metadata:
      labels:
        app: app-97daf9913d0d
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:alpine
        name: web
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: app-97daf9913d0d-svc
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-97daf9913d0d
  type: NodePort
